/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

import com.cinema.controll.PhimControllInsert;
import com.cinema.controll.PhimControllUpdate;
import com.cinema.dao.PhimDAO;
import com.cinema.dialog.AvatarDialog;
import com.cinema.dialog.ChonPhim;
import com.cinema.dialog.IPopupDialog;
import com.cinema.model.Phim;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thanh
 */
public class QuanLyPhim extends javax.swing.JPanel {

    PhimDAO dao = new PhimDAO();
    List<Phim> list = new ArrayList<>();
    JPopupMenu popupMenu = new JPopupMenu();
    private PhimControllUpdate jlabel;
    private PhimControllUpdate jtextfield1;
    private PhimControllUpdate jcombobox;
    
    public QuanLyPhim() {
        initComponents();
        this.fillToTable();
    }

    private void addPopupView() {
        AvatarDialog avtDialog = new AvatarDialog(null, true, tblView);
        
        JMenuItem avtItem = new JMenuItem("Xem avatar");
        avtItem.addActionListener(new InsertRowsActionAdapter(avtDialog));
        popupMenu.add(avtItem);

        tblView.setComponentPopupMenu(popupMenu);
        tblView.addMouseListener(new PopupListener());

    }

    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        model.setRowCount(0);
        try {
            list = dao.select();
            for (Phim pm : list) {
                Object[] row = {
                    pm.getMaPhim(),
                    pm.getTenPhim(),
                    pm.getNhaSanXuat(),
                    pm.getDoTuoi(),
                    pm.getThoiLuong(),
                    pm.getNgayCongChieu(),
                    pm.getPoster()
                };
                model.addRow(row);
            }
            addPopupView();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void Search(String text) {
        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        model.setRowCount(0);
        try {
            for (Phim pm : list) {
                if (pm.getTenPhim().contains(text)) {
                    Object[] row = new Object[]{
                        pm.getMaPhim(),
                        pm.getTenPhim(),
                        pm.getNhaSanXuat(),
                        pm.getDoTuoi(),
                        pm.getThoiLuong(),
                        pm.getNgayCongChieu(),
                        pm.getPoster()
                    };
                    model.addRow(row);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void delete(int i) {
        try {
            String index = String.valueOf(tblView.getValueAt(i, 0));
            dao.delete(index);
            fillToTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Phim này đã công chiếu");
        }
    }

    public PhimControllUpdate getJlabel() {
        return jlabel;
    }

    public void setJlabel(PhimControllUpdate jlabel) {
        this.jlabel = jlabel;
    }

    public PhimControllUpdate getJtextfield1() {
        return jtextfield1;
    }

    public void setJtextfield1(PhimControllUpdate jtextfield1) {
        this.jtextfield1 = jtextfield1;
    }

    public PhimControllUpdate getJcombobox() {
        return jcombobox;
    }

    public void setJcombobox(PhimControllUpdate jcombobox) {
        this.jcombobox = jcombobox;
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1290, 770));
        setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinema/image/searchIcon.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        add(jLabel4);
        jLabel4.setBounds(20, 10, 54, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        add(jLabel1);
        jLabel1.setBounds(1180, 10, 90, 48);

        tblView.setBackground(new java.awt.Color(0, 102, 102));
        tblView.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tblView.setForeground(new java.awt.Color(255, 255, 255));
        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ PHIM", "TÊN PHIM", "NHÀ SẢN XUẤT", "ĐỘ TUỔI", "THỜI LƯỢNG", "NGÀY CÔNG CHIẾU", "POSTER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblView.setRowHeight(37);
        tblView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblView);
        tblView.getAccessibleContext().setAccessibleDescription("");

        add(jScrollPane1);
        jScrollPane1.setBounds(12, 68, 1266, 685);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Xóa");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2);
        jLabel2.setBounds(980, 10, 90, 48);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sửa");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        add(jLabel3);
        jLabel3.setBounds(1080, 10, 90, 48);

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        add(txtSearch);
        txtSearch.setBounds(70, 10, 216, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        this.Search(txtSearch.getText());
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int index = tblView.getSelectedRow();
        ChonPhim cp = new ChonPhim(null, true);
        if (index != -1) {
            this.delete(index);
        } else {
            cp.setVisible(true);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        PhimControllInsert pi = new PhimControllInsert(null, true);
        pi.setJpanel(this);
        pi.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tblViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewMouseClicked
        PhimControllUpdate pUpdate = new PhimControllUpdate(null, true);
        int index = tblView.getSelectedRow();
        Phim pm = list.get(index);
        
        
    }//GEN-LAST:event_tblViewMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    class PopupListener extends MouseAdapter {      
        
        @Override
        public void mousePressed(MouseEvent e) {
            showPopup(e);
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            showPopup(e);            
        }

        private void showPopup(MouseEvent e) {
            int r = tblView.rowAtPoint(e.getPoint());
            if (r >= 0 && r < tblView.getRowCount()) {
                tblView.setRowSelectionInterval(r, r);
            } else {
                tblView.clearSelection();
            }
            int rowindex = tblView.getSelectedRow();
            if (rowindex < 0) {
                return;
            }
            if (e.isPopupTrigger() && e.getComponent() instanceof JTable) {
                popupMenu.show(e.getComponent(), e.getX(), e.getY());
            }
        }
    }
}

class InsertRowsActionAdapter<T extends IPopupDialog> implements ActionListener {

    T dialog;

    InsertRowsActionAdapter(T adaptee) {
        this.dialog = adaptee;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        dialog.actionAfterClick(e);
    }
}
