/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema;

import com.cinema.dao.GiaVeDAO;
import com.cinema.dialog.ChonGiaVe;
import com.cinema.model.GiaVe;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thanh
 */
public class QuanLyGiaVe extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyGiaVe
     */
    GiaVeDAO dao = new GiaVeDAO();
    List<GiaVe> list = new ArrayList<>();

    public QuanLyGiaVe() {
        initComponents();
        this.fillToTable();
    }

    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        model.setRowCount(0);
        try {
            list = dao.select();
            for (GiaVe gv : list) {
                Object row[]
                        = {
                            gv.getMaGiaVe(),
                            gv.getGiaVe(),
                            gv.getMoTa()
                        };
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void search(String a) {
        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        model.setRowCount(0);
        try {
            for (GiaVe gv : list) {
                if (gv.getMoTa().contains(a)) {
                    Object[] row = new Object[]{
                        gv.getMaGiaVe(),
                        gv.getGiaVe(),
                        gv.getMoTa()
                    };
                    model.addRow(row);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    
    public void delete(int i){
        try {
            String index = String.valueOf(tblView.getValueAt(i, 0));
            dao.delete(index);
            fillToTable();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1290, 770));
        setLayout(null);

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        txtSearch.setMargin(new java.awt.Insets(2, 8, 2, 8));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        add(txtSearch);
        txtSearch.setBounds(70, 10, 216, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("XÓA");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        add(jLabel1);
        jLabel1.setBounds(1098, 14, 84, 48);

        tblView.setBackground(new java.awt.Color(0, 102, 102));
        tblView.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tblView.setForeground(new java.awt.Color(255, 255, 255));
        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ GIÁ VÉ", "GIÁ VÉ", "MÔ TẢ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblView.setRowHeight(37);
        jScrollPane1.setViewportView(tblView);

        add(jScrollPane1);
        jScrollPane1.setBounds(12, 77, 1266, 680);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thêm");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        add(jLabel4);
        jLabel4.setBounds(1194, 13, 84, 48);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SỬA");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        add(jLabel5);
        jLabel5.setBounds(1002, 13, 84, 48);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cinema/image/searchIcon.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        add(jLabel2);
        jLabel2.setBounds(20, 10, 54, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        this.search(txtSearch.getText());
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        int index = tblView.getSelectedRow();
        ChonGiaVe gv = new ChonGiaVe(null, true);
        if (index != -1) {
            this.delete(index);
        }else{
            gv.setVisible(true);
        }
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
